spring:
  application:
    name: tcs-srv-treinamento-ms

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

# INICIO - ACTUATOR PROPERTIES
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
    exposure:
      include: health
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, ping
      show-details: "NEVER"
      probes:
        enabled: true
  health:
    ping:
      enabled: true
    diskspace:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    servicosDependentes:
      enabled: false
    redis:
      enabled: false
  # Rastreabilidade com Micrometer
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
# FIM - ACTUATOR PROPERTIES